# Generated by Django 6.0.4 on 2026-05-12 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0008_add_gymclass_gymschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', max_length=10)),
                ('currency', models.CharField(choices=[('BDT', 'BDT — Tk.'), ('USD', 'USD — $')], default='BDT', max_length=10)),
                ('date_format', models.CharField(choices=[('dmy', 'DD/MM/YYYY'), ('mdy', 'MM/DD/YYYY')], default='dmy', max_length=20)),
                ('week_start', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('sat', 'Saturday')], default='sat', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gym Preferences',
            },
        ),
        migrations.CreateModel(
            name='GymProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('website', models.URLField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gym Profile',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_received', models.BooleanField(default=True)),
                ('new_member_signup', models.BooleanField(default=True)),
                ('reminder_due', models.BooleanField(default=True)),
                ('weekly_report', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='ReminderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('reminder_type', models.CharField(choices=[('payment_due', 'Payment Due'), ('package_expiry', 'Package Expiry'), ('overdue_notice', 'Overdue Notice'), ('renewal', 'Renewal')], max_length=30)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('both', 'Both')], default='email', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('days_before', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['reminder_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('payment_due', 'Payment Due'), ('package_expiry', 'Package Expiry'), ('partial_payment', 'Partial Payment'), ('renewal', 'Renewal')], max_length=30)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('both', 'Both')], default='email', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='membership.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
