# Generated by Django 6.0.4 on 2026-05-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_gymprofile_logo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gympreferences',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা (Bengali)'), ('hi', 'हिंदी (Hindi)'), ('ar', 'العربية (Arabic)'), ('ur', 'اردو (Urdu)'), ('zh', '中文 (Chinese)'), ('ja', '日本語 (Japanese)'), ('ko', '한국어 (Korean)'), ('fr', 'Français (French)'), ('es', 'Español (Spanish)'), ('de', 'Deutsch (German)'), ('pt', 'Português (Portuguese)'), ('ru', 'Русский (Russian)'), ('tr', 'Türkçe (Turkish)')], default='en', max_length=10),
        ),
    ]
