# Generated by Django 6.0.4 on 2026-05-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_platform_settings_default_language_expand_language_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gympreferences',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD — $'), ('EUR', 'EUR — €'), ('GBP', 'GBP — £'), ('BDT', 'BDT — Tk.'), ('INR', 'INR — ₹'), ('AUD', 'AUD — A$'), ('CAD', 'CAD — C$'), ('SGD', 'SGD — S$'), ('AED', 'AED — AED'), ('SAR', 'SAR — SR'), ('OMR', 'OMR — OMR'), ('QAR', 'QAR — QR'), ('KWD', 'KWD — KD'), ('BHD', 'BHD — BD'), ('MYR', 'MYR — RM'), ('IDR', 'IDR — Rp'), ('CNY', 'CNY — ¥'), ('JPY', 'JPY — ¥'), ('TRY', 'TRY — ₺'), ('RUB', 'RUB — ₽'), ('ZAR', 'ZAR — R'), ('BRL', 'BRL — R$')], default='USD', max_length=10),
        ),
    ]
