# Generated by Django 6.0.4 on 2026-08-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_gympreferences_payment_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymprofile',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='gymprofile',
            name='secondary_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
