"""Sync verified tenant custom domains into Traefik file-provider config.

Traefik cannot infer ACME domains from ``HostRegexp`` catch-all routers, so each
verified custom hostname must get an explicit ``Host(`…`)`` router with
``tls.certResolver: customdomains`` (HTTP-01). This module regenerates that
YAML atomically whenever domains are verified or removed.
"""
from __future__ import annotations

import logging
import os
import re
import tempfile
from pathlib import Path

from django.conf import settings
from django_tenants.utils import get_public_schema_name, schema_context

logger = logging.getLogger(__name__)

# Platform hosts are covered by the Hostinger DNS-01 ``letsencrypt`` resolver.
_PLATFORM_SUFFIXES = ("fitssort.com",)

_DOMAIN_RE = re.compile(
    r"^(?=.{1,253}$)(?!-)([a-z0-9-]{1,63}\.)+[a-z]{2,63}$"
)

_FRONTEND_EXCLUDES = (
    "!PathPrefix(`/api`)",
    "!PathPrefix(`/admin`)",
    "!PathPrefix(`/media`)",
    "!PathPrefix(`/static`)",
    "!PathPrefix(`/ws`)",
    "!PathPrefix(`/iclock`)",
    "!PathPrefix(`/cdata`)",
    "!PathPrefix(`/getrequest`)",
    "!PathPrefix(`/devicecmd`)",
)

_API_PATHS = (
    "PathPrefix(`/api`)",
    "PathPrefix(`/admin`)",
    "PathPrefix(`/media`)",
    "PathPrefix(`/static`)",
)


def _output_path() -> Path:
    raw = (
        getattr(settings, "TRAEFIK_CUSTOM_DOMAINS_PATH", "") or ""
    ).strip() or "/traefik-dynamic/custom-domains.yml"
    return Path(raw)


def _is_platform_domain(domain: str) -> bool:
    d = (domain or "").strip().lower().rstrip(".")
    return any(d == s or d.endswith("." + s) for s in _PLATFORM_SUFFIXES)


def _normalize_domain(domain: str) -> str:
    return (domain or "").strip().lower().rstrip(".")


def _slug(domain: str) -> str:
    """Safe Traefik router name fragment from a hostname."""
    return re.sub(r"[^a-z0-9]+", "-", _normalize_domain(domain)).strip("-")[:80]


def _valid_domain(domain: str) -> bool:
    d = _normalize_domain(domain)
    return bool(d) and bool(_DOMAIN_RE.match(d)) and not _is_platform_domain(d)


def list_verified_custom_domains() -> list[str]:
    """Return sorted unique verified custom hostnames (public schema)."""
    from apps.tenancy.models import CustomDomainRequest, Domain

    with schema_context(get_public_schema_name()):
        from_requests = set(
            CustomDomainRequest.objects.filter(
                status=CustomDomainRequest.STATUS_VERIFIED
            ).values_list("domain", flat=True)
        )
        # Also include secondary Domain rows that are not platform suffixes
        # (covers aliases created before CustomDomainRequest existed).
        from_domains = set(
            Domain.objects.filter(is_primary=False).values_list("domain", flat=True)
        )

    domains = sorted(
        {
            _normalize_domain(d)
            for d in from_requests | from_domains
            if _valid_domain(d)
        }
    )
    return domains


def render_custom_domains_yaml(domains: list[str]) -> str:
    """Build Traefik dynamic YAML for the given hostnames."""
    lines: list[str] = [
        "# AUTO-GENERATED by apps.tenancy.traefik_custom_domains — do not edit.",
        "# Explicit Host() routers so the customdomains HTTP-01 ACME resolver",
        "# can issue Let's Encrypt certs (HostRegexp cannot drive ACME).",
        "",
    ]
    if not domains:
        lines.extend(
            [
                "# No verified custom domains.",
                "http:",
                "  routers: {}",
                "",
            ]
        )
        return "\n".join(lines)

    lines.append("http:")
    lines.append("  routers:")

    for domain in domains:
        slug = _slug(domain)
        host = f"Host(`{domain}`)"
        fe_rule = " && ".join([host, *_FRONTEND_EXCLUDES])
        api_rule = f"{host} && ({' || '.join(_API_PATHS)})"
        ws_rule = f"{host} && PathPrefix(`/ws`)"
        http_rule = (
            f"{host} && !PathPrefix(`/.well-known/acme-challenge/`) "
            f"&& !PathPrefix(`/iclock`) && !PathPrefix(`/cdata`) "
            f"&& !PathPrefix(`/getrequest`) && !PathPrefix(`/devicecmd`)"
        )

        # HTTPS frontend (priority above catch-all frontend-custom=1)
        lines.append(f"    cd-{slug}-https:")
        lines.append(f"      rule: \"{fe_rule}\"")
        lines.append("      entryPoints:")
        lines.append("        - websecure")
        lines.append("      service: frontend@docker")
        lines.append("      priority: 50")
        lines.append("      middlewares:")
        lines.append("        - security-headers@file")
        lines.append("        - compress@file")
        lines.append("      tls:")
        lines.append("        certResolver: customdomains")

        # HTTPS API
        lines.append(f"    cd-{slug}-api:")
        lines.append(f"      rule: \"{api_rule}\"")
        lines.append("      entryPoints:")
        lines.append("        - websecure")
        lines.append("      service: backend@docker")
        lines.append("      priority: 110")
        lines.append("      middlewares:")
        lines.append("        - security-headers@file")
        lines.append("        - compress@file")
        lines.append("        - api-ratelimit@file")
        lines.append("      tls:")
        lines.append("        certResolver: customdomains")

        # HTTPS WebSocket
        lines.append(f"    cd-{slug}-ws:")
        lines.append(f"      rule: \"{ws_rule}\"")
        lines.append("      entryPoints:")
        lines.append("        - websecure")
        lines.append("      service: backend-ws@docker")
        lines.append("      priority: 110")
        lines.append("      middlewares:")
        lines.append("        - security-headers@file")
        lines.append("        - ws-headers@file")
        lines.append("      tls:")
        lines.append("        certResolver: customdomains")

        # HTTP → HTTPS (leave ACME + ADMS on port 80)
        lines.append(f"    cd-{slug}-http:")
        lines.append(f"      rule: \"{http_rule}\"")
        lines.append("      entryPoints:")
        lines.append("        - web")
        lines.append("      middlewares:")
        lines.append("        - redirect-to-https@file")
        lines.append("      service: frontend@docker")
        lines.append("      priority: 50")

    lines.append("")
    return "\n".join(lines)


def sync_traefik_custom_domains(*, path: Path | None = None) -> Path | None:
    """Regenerate Traefik custom-domain routers. Returns the written path or None."""
    out = path or _output_path()
    domains = list_verified_custom_domains()
    content = render_custom_domains_yaml(domains)

    try:
        out.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp_name = tempfile.mkstemp(
            dir=str(out.parent), prefix=".custom-domains.", suffix=".yml.tmp"
        )
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(content)
                fh.flush()
                os.fsync(fh.fileno())
            os.replace(tmp_name, out)
        except Exception:
            try:
                os.unlink(tmp_name)
            except OSError:
                pass
            raise
    except OSError as exc:
        logger.exception(
            "Failed to write Traefik custom-domains config to %s: %s", out, exc
        )
        return None

    logger.info(
        "Synced %d Traefik custom domain(s) to %s", len(domains), out
    )
    return out
