# Generated by Django 6.0.4 on 2026-05-30 14:14

import django.db.models.deletion
from django.db import migrations, models


def assign_trainers_to_main_branch(apps, schema_editor):
    TrainerProfile = apps.get_model('trainer', 'TrainerProfile')
    Branch = apps.get_model('gym_branch', 'Branch')

    default_branch = Branch.objects.filter(name='Main Branch').first()
    if default_branch is None:
        default_branch = Branch.objects.order_by('id').first()
    if default_branch is None:
        default_branch = Branch.objects.create(name='Main Branch', status='active')

    TrainerProfile.objects.filter(branch__isnull=True).update(branch=default_branch)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gym_branch', '0001_initial'),
        ('trainer', '0002_alter_trainerdocument_document_url'),
        ('main_app', '0002_remove_gymclub_facilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='gym_branch.branch'),
        ),
        migrations.RunPython(assign_trainers_to_main_branch, noop_reverse),
    ]
