# Generated by Django 6.0.4 on 2026-06-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_branch', '0001_initial'),
        ('trainer', '0003_trainerprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerinvitation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_invitations', to='gym_branch.branch'),
        ),
    ]
