# Generated by Django 6.0.4 on 2026-07-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_expense_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='voucher_no',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Expense voucher number assigned on create (e.g. EXP-000001).', max_length=40),
        ),
    ]
