# Generated by Django 6.0.4 on 2026-05-04

from django.db import migrations, models


def copy_tenant_user_names_to_invitations(apps, schema_editor):
    Invitation = apps.get_model('tenancy', 'Invitation')
    for invitation in Invitation.objects.select_related('tenant_user').filter(tenant_user__isnull=False):
        full_name = getattr(invitation.tenant_user, 'full_name', '') or ''
        if full_name and not invitation.invitee_full_name:
            invitation.invitee_full_name = full_name
            invitation.save(update_fields=['invitee_full_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_tenant_is_enabled_tenantuser_invitation_emailqueue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitee_full_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.RunPython(copy_tenant_user_names_to_invitations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='invitation',
            name='tenant_user',
        ),
        migrations.DeleteModel(
            name='TenantUser',
        ),
    ]
