# Generated by Django 6.0.4 on 2026-05-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_remove_tenantuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invitations',
                to='tenancy.tenant',
            ),
        ),
    ]
