# Generated by Django 6.0.4 on 2026-05-08 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_alter_invitation_tenant_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_users', models.IntegerField(default=10)),
                ('max_branches', models.IntegerField(default=1)),
                ('trial_days', models.IntegerField(default=0, help_text='Free trial length in days; 0 = no trial.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Show on public pricing page.')),
                ('sort_order', models.IntegerField(default=0)),
                ('highlight', models.BooleanField(default=False, help_text="Visually highlighted plan (e.g. 'most popular').")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='PlatformRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted.')),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_system', models.BooleanField(default=False, help_text='System features cannot be disabled.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tenancy.feature')),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='platform_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='tenancy.platformrole'),
        ),
        migrations.CreateModel(
            name='PlatformPackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_features', to='tenancy.feature')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_features', to='tenancy.platformpackage')),
            ],
            options={
                'unique_together': {('package', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='PlatformRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(max_length=80)),
                ('permission_level', models.CharField(choices=[('none', 'None'), ('view', 'View'), ('edit', 'Edit'), ('full', 'Full')], default='none', max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tenancy.platformrole')),
            ],
            options={
                'indexes': [models.Index(fields=['module_key'], name='idx_platrp_module')],
                'unique_together': {('role', 'module_key')},
            },
        ),
        migrations.CreateModel(
            name='PlatformUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='tenancy.platformrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='TenantFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('package', 'Package'), ('superadmin_override', 'Superadmin Override')], default='package', max_length=30)),
                ('grace_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_flags', to='tenancy.feature')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_enabled'], name='idx_tff_tenant_enabled')],
                'unique_together': {('tenant', 'feature')},
            },
        ),
    ]
