# Generated by Django 6.0.4 on 2026-05-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_platformpackage_platformrole_feature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformuserrole',
            options={'ordering': ['-assigned_at']},
        ),
    ]
