# Generated by Django 6.0.4 on 2026-05-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_platformuserrole_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token_type',
            field=models.CharField(choices=[('verification', 'Verification'), ('invitation', 'Invitation'), ('password_reset', 'Password Reset'), ('platform_invite', 'Platform Team Invitation')], max_length=20),
        ),
    ]
