# Generated by Django 6.0.4 on 2026-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_platformpackage_pricing_customization'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Stable identifier, e.g. 'sslcommerz'.", unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('is_enabled_for_tenants', models.BooleanField(default=False, help_text='When True, tenants can configure and use this gateway.')),
                ('config_schema', models.JSONField(blank=True, default=list, help_text="List of field descriptors that define the credential form tenants must fill in. Each entry: {key, label, type ('text'|'password'|'boolean'), required (bool)}.")),
                ('platform_credentials', models.JSONField(blank=True, default=dict, help_text='Platform-level credentials for processing SaaS subscription payments (write-only in API).')),
                ('is_sandbox', models.BooleanField(default=True, help_text='When True, platform-level credentials point to the sandbox/test environment.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='platformpackage',
            name='included_items',
            field=models.JSONField(blank=True, default=list, help_text="Manually typed 'What's included' list. Overrides auto-generated feature names when non-empty."),
        ),
    ]
