# Generated by Django 6.0.4 on 2026-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0015_mark_sslcommerz_as_default_subscription_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_timezone', models.CharField(default='Asia/Dhaka', help_text='IANA timezone used as the default for all tenants that have not set their own.', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.AlterField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='Asia/Dhaka', max_length=50),
        ),
    ]
