# Generated by Django 6.0.4 on 2026-05-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0016_add_platform_settings_and_tenant_tz_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformGymPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', max_length=10)),
                ('currency', models.CharField(choices=[('BDT', 'BDT — Tk.'), ('USD', 'USD — $')], default='BDT', max_length=10)),
                ('date_format', models.CharField(choices=[('dmy', 'DD/MM/YYYY'), ('mdy', 'MM/DD/YYYY')], default='dmy', max_length=20)),
                ('week_start', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('sat', 'Saturday')], default='sat', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Gym Preferences',
            },
        ),
        migrations.CreateModel(
            name='PlatformGymProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('website', models.URLField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('logo_url', models.URLField(blank=True, default='', max_length=1000)),
                ('logo_width', models.PositiveIntegerField(default=120)),
                ('logo_height', models.PositiveIntegerField(default=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Gym Profile',
            },
        ),
        migrations.CreateModel(
            name='PlatformNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_received', models.BooleanField(default=True)),
                ('new_member_signup', models.BooleanField(default=True)),
                ('reminder_due', models.BooleanField(default=True)),
                ('weekly_report', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Notification Preferences',
            },
        ),
    ]
