# Generated by Django 6.0.4 on 2026-05-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0017_platform_gym_profile_preferences_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='default_language',
            field=models.CharField(default='en', help_text='ISO 639-1 language code used as the default for all tenants that have not set their own.', max_length=10),
        ),
        migrations.AlterField(
            model_name='platformgympreferences',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা (Bengali)'), ('hi', 'हिंदी (Hindi)'), ('ar', 'العربية (Arabic)'), ('ur', 'اردو (Urdu)'), ('zh', '中文 (Chinese)'), ('ja', '日本語 (Japanese)'), ('ko', '한국어 (Korean)'), ('fr', 'Français (French)'), ('es', 'Español (Spanish)'), ('de', 'Deutsch (German)'), ('pt', 'Português (Portuguese)'), ('ru', 'Русский (Russian)'), ('tr', 'Türkçe (Turkish)')], default='en', max_length=10),
        ),
    ]
