# Generated by Django 6.0.4 on 2026-05-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0018_add_platform_settings_default_language_expand_language_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='default_currency',
            field=models.CharField(default='USD', help_text='Currency code used as the default for all tenants that have not set their own.', max_length=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_currency_conversion',
            field=models.BooleanField(default=True, help_text='Enable or disable dynamic currency conversion based on the dollar rate or custom rates.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='exchange_rates',
            field=models.JSONField(blank=True, default=dict, help_text="Dynamic exchange rate matrix with USD as the base currency. E.g. {'EUR': 0.92, 'INR': 83.50, 'BDT': 120.0}"),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='usd_to_bdt_rate',
            field=models.DecimalField(decimal_places=4, default=120.0, help_text='Default USD to BDT exchange rate.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='platformgympreferences',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD — $'), ('EUR', 'EUR — €'), ('GBP', 'GBP — £'), ('BDT', 'BDT — Tk.'), ('INR', 'INR — ₹'), ('AUD', 'AUD — A$'), ('CAD', 'CAD — C$'), ('SGD', 'SGD — S$'), ('AED', 'AED — AED'), ('SAR', 'SAR — SR'), ('OMR', 'OMR — OMR'), ('QAR', 'QAR — QR'), ('KWD', 'KWD — KD'), ('BHD', 'BHD — BD'), ('MYR', 'MYR — RM'), ('IDR', 'IDR — Rp'), ('CNY', 'CNY — ¥'), ('JPY', 'JPY — ¥'), ('TRY', 'TRY — ₺'), ('RUB', 'RUB — ₽'), ('ZAR', 'ZAR — R'), ('BRL', 'BRL — R$')], default='USD', max_length=10),
        ),
    ]
