# Generated by Django 6.0.4 on 2026-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0019_platformsettings_default_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpackage',
            name='max_members_per_branch',
            field=models.IntegerField(default=0, help_text='Maximum members per branch. 0 means unlimited.'),
        ),
        migrations.AddField(
            model_name='platformpackage',
            name='max_trainers_per_branch',
            field=models.IntegerField(default=0, help_text='Maximum trainers per branch. 0 means unlimited.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_members_per_branch',
            field=models.IntegerField(default=0, help_text='Maximum members per branch. 0 means unlimited.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_trainers_per_branch',
            field=models.IntegerField(default=0, help_text='Maximum trainers per branch. 0 means unlimited.'),
        ),
    ]
