# Generated by Django 6.0.4 on 2026-06-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0022_platformpackage_cta_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpackage',
            name='max_employees_per_branch',
            field=models.IntegerField(default=0, help_text='Maximum employees (staff) per branch. 0 means unlimited.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_custom_domains',
            field=models.BooleanField(default=False, help_text='Global master switch. When True, tenants that are individually enabled may connect their own custom domains.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_domain_enabled',
            field=models.BooleanField(default=False, help_text='When True, this tenant may connect its own custom domain from Settings.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_employees_per_branch',
            field=models.IntegerField(default=0, help_text='Maximum employees (staff) per branch. 0 means unlimited.'),
        ),
        migrations.CreateModel(
            name='CustomDomainRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('verification_token', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='pending', max_length=20)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domain_requests', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='idx_cdr_tenant_status')],
            },
        ),
    ]
