# Generated by Django 6.0.4 on 2026-06-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0023_platformpackage_max_employees_per_branch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessDeviceRoute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("access_device_id", models.PositiveBigIntegerField()),
                ("device_sn", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_device_routes",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["device_sn"],
                "indexes": [
                    models.Index(fields=["tenant", "is_active"], name="idx_adr_tenant_active"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "access_device_id"),
                        name="uniq_access_device_route_per_device",
                    ),
                ],
            },
        ),
    ]
