# Generated by Django 6.0.4 on 2026-08-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0030_seed_stripe_gateway_clear_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformgymprofile',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='platformgymprofile',
            name='secondary_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='is_default_for_subscriptions',
            field=models.BooleanField(default=False, help_text='Deprecated: no gateway is used as an implicit default. Callers must choose a gateway_slug explicitly for each payment.'),
        ),
    ]
