# Generated by Django 6.0.4 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0032_platform_overview_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentgateway",
            name="is_default_for_subscriptions",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Deprecated: no gateway is used as an implicit default. "
                    "Callers must choose a gateway_slug explicitly for each payment."
                ),
            ),
        ),
    ]
