# Generated by Django 5.2 on 2026-02-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0006_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='admission_fee',
        ),
    ]
