# Generated by Django 6.0.4 on 2026-05-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_tenant_is_enabled_tenantuser_invitation_emailqueue_and_more'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                help_text='Tenant this user belongs to. Public platform users can leave this empty.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users',
                to='tenancy.tenant',
            ),
        ),
    ]
