# Generated by Django 6.0.4 on 2026-05-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_user_email_verified_user_password_set_at_user_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('trainer', 'Trainer'), ('staff', 'Staff'), ('admin', 'Admin'), ('superuser', 'Superuser')], default='student', max_length=20),
        ),
    ]
