"""Billing API views.

- Platform package endpoints (`/billing/packages`, `/billing/features`) are
    intended for public-schema platform admin usage and are gated by
    `platform.packages` permissions.
- Tenant payment endpoints (`/billing/payments/*`) run on tenant schemas and
    are gated by tenant feature permission key `payments`.
"""
from datetime import timedelta
from decimal import Decimal
from io import BytesIO

from django.db import transaction
from django.db.models import Count, Sum, Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from rest_framework import status
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.renderers import BaseRenderer, JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from django_filters.rest_framework import DjangoFilterBackend

from apps.access.permissions import HasFeatureMethodPermission
from apps.membership.models import Member, Payment
from apps.tenancy.models import (
    Feature,
    PlatformPackage,
    PlatformPackageFeature,
)
from apps.tenancy.permissions import IsPlatformFeaturePermission
from utils.base_view import ModelCRUDView

from .serializers import (
    FeatureSerializer,
    PackageFeatureBulkSerializer,
    PackageSerializer,
    PaymentSerializer,
    PaymentMemberOptionSerializer,
)


def _render_payment_invoice_pdf(payment: Payment, tenant_name: str, generated_by: str) -> bytes:
    # Lazy import keeps startup resilient if dependency installation is pending.
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    width, height = A4
    left = 20 * mm
    right = width - (20 * mm)
    top = height - (20 * mm)

    invoice_no = payment.invoice_no or f"INV-{payment.id:06d}"
    member = payment.member
    package_name = member.member_package.name if member.member_package else "General"
    amount = f"TK. {payment.amount}"
    payment_date = timezone.localtime(payment.payment_date).strftime("%d %b %Y, %I:%M %p")

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)

    brand_primary = colors.HexColor("#0F172A")
    brand_accent = colors.HexColor("#0EA5E9")
    brand_soft = colors.HexColor("#F1F5F9")
    text_main = colors.HexColor("#111827")
    text_muted = colors.HexColor("#64748B")

    pdf.setFillColor(brand_primary)
    pdf.rect(0, height - (42 * mm), width, 42 * mm, fill=1, stroke=0)

    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 21)
    pdf.drawString(left, top - (4 * mm), tenant_name or "Gym Management")
    pdf.setFont("Helvetica", 10)
    pdf.drawString(left, top - (11 * mm), "Payment Invoice")

    pdf.setFillColor(brand_accent)
    pdf.roundRect(right - (56 * mm), top - (16 * mm), 56 * mm, 11 * mm, 3 * mm, fill=1, stroke=0)
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawCentredString(right - (28 * mm), top - (9.5 * mm), "MANUAL PAYMENT")

    y = top - (34 * mm)
    pdf.setFillColor(text_main)
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(left, y, "Invoice Information")

    y -= 8 * mm
    pdf.setFillColor(brand_soft)
    pdf.roundRect(left, y - (30 * mm), right - left, 30 * mm, 2 * mm, fill=1, stroke=0)

    pdf.setFillColor(text_muted)
    pdf.setFont("Helvetica", 9)
    pdf.drawString(left + (4 * mm), y - (5 * mm), "Invoice No")
    pdf.drawString(left + (72 * mm), y - (5 * mm), "Date")
    pdf.drawString(left + (125 * mm), y - (5 * mm), "Generated By")

    pdf.setFillColor(text_main)
    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(left + (4 * mm), y - (11 * mm), invoice_no)
    pdf.setFont("Helvetica", 10)
    pdf.drawString(left + (72 * mm), y - (11 * mm), payment_date)
    pdf.drawString(left + (125 * mm), y - (11 * mm), generated_by)

    pdf.setFillColor(text_muted)
    pdf.setFont("Helvetica", 9)
    pdf.drawString(left + (4 * mm), y - (21 * mm), "Member")
    pdf.drawString(left + (72 * mm), y - (21 * mm), "Contact")
    pdf.drawString(left + (125 * mm), y - (21 * mm), "Package")

    pdf.setFillColor(text_main)
    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(left + (4 * mm), y - (27 * mm), member.full_name)
    pdf.setFont("Helvetica", 10)
    pdf.drawString(left + (72 * mm), y - (27 * mm), member.phone_number)
    pdf.drawString(left + (125 * mm), y - (27 * mm), package_name)

    y -= 44 * mm
    pdf.setFillColor(text_main)
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(left, y, "Charge Summary")

    y -= 6 * mm
    table_h = 26 * mm
    pdf.setStrokeColor(colors.HexColor("#CBD5E1"))
    pdf.roundRect(left, y - table_h, right - left, table_h, 2 * mm, fill=0, stroke=1)

    pdf.setFillColor(text_muted)
    pdf.setFont("Helvetica", 9)
    pdf.drawString(left + (4 * mm), y - (5 * mm), "Item")
    pdf.drawString(left + (95 * mm), y - (5 * mm), "Method")
    pdf.drawString(left + (125 * mm), y - (5 * mm), "Status")
    pdf.drawRightString(right - (4 * mm), y - (5 * mm), "Amount")

    pdf.setFillColor(text_main)
    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(left + (4 * mm), y - (12 * mm), payment.get_payment_type_display())
    pdf.setFont("Helvetica", 10)
    pdf.drawString(left + (95 * mm), y - (12 * mm), payment.get_payment_method_display())
    pdf.drawString(left + (125 * mm), y - (12 * mm), payment.get_payment_status_display())
    pdf.drawRightString(right - (4 * mm), y - (12 * mm), amount)

    pdf.setStrokeColor(colors.HexColor("#E2E8F0"))
    pdf.line(left + (4 * mm), y - (16 * mm), right - (4 * mm), y - (16 * mm))
    pdf.setFillColor(text_main)
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(left + (4 * mm), y - (23 * mm), "Total")
    pdf.drawRightString(right - (4 * mm), y - (23 * mm), amount)

    y -= 36 * mm
    pdf.setFillColor(text_muted)
    pdf.setFont("Helvetica", 9)
    pdf.drawString(left, y, "Notes")
    pdf.setFillColor(text_main)
    pdf.setFont("Helvetica", 10)
    notes = payment.note or "No additional notes."
    pdf.drawString(left, y - (5 * mm), notes[:110])

    pdf.setFillColor(brand_soft)
    pdf.rect(0, 0, width, 20 * mm, fill=1, stroke=0)
    pdf.setFillColor(text_muted)
    pdf.setFont("Helvetica", 9)
    pdf.drawCentredString(width / 2, 8 * mm, "Thank you for your payment. This invoice is system-generated.")

    pdf.showPage()
    pdf.save()
    return buffer.getvalue()


PACKAGE_VIEW_PERMS = [
    IsPlatformFeaturePermission.require("platform.packages", "view"),
]
PACKAGE_EDIT_PERMS = [
    IsPlatformFeaturePermission.require("platform.packages", "edit"),
]


class FeatureListAPIView(APIView):
    """GET /api/v1/billing/features/ — list all known features."""

    permission_classes = PACKAGE_VIEW_PERMS

    def get(self, request):
        features = Feature.objects.all().order_by("sort_order", "key")
        return Response(FeatureSerializer(features, many=True).data)


class PackageListCreateAPIView(APIView):
    """GET / POST /api/v1/billing/packages/."""

    def get_permissions(self):
        if self.request.method == "POST":
            return [perm() for perm in PACKAGE_EDIT_PERMS]
        return [perm() for perm in PACKAGE_VIEW_PERMS]

    def get(self, request):
        packages = (
            PlatformPackage.objects.all()
            .prefetch_related("package_features__feature")
            .order_by("sort_order", "price_monthly")
        )
        return Response(PackageSerializer(packages, many=True).data)

    def post(self, request):
        serializer = PackageSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        with transaction.atomic():
            package = serializer.save()
        return Response(
            PackageSerializer(package).data,
            status=status.HTTP_201_CREATED,
        )


class PackageDetailAPIView(APIView):
    """GET / PATCH / PUT / DELETE /api/v1/billing/packages/{pk}/."""

    def get_permissions(self):
        if self.request.method in ("GET", "HEAD", "OPTIONS"):
            return [perm() for perm in PACKAGE_VIEW_PERMS]
        return [perm() for perm in PACKAGE_EDIT_PERMS]

    def _get_object(self, pk):
        return get_object_or_404(
            PlatformPackage.objects.prefetch_related("package_features__feature"),
            pk=pk,
        )

    def get(self, request, pk):
        return Response(PackageSerializer(self._get_object(pk)).data)

    def patch(self, request, pk):
        package = self._get_object(pk)
        serializer = PackageSerializer(package, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        with transaction.atomic():
            package = serializer.save()
        return Response(PackageSerializer(package).data)

    def put(self, request, pk):
        package = self._get_object(pk)
        serializer = PackageSerializer(package, data=request.data)
        serializer.is_valid(raise_exception=True)
        with transaction.atomic():
            package = serializer.save()
        return Response(PackageSerializer(package).data)

    def delete(self, request, pk):
        package = self._get_object(pk)
        package.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class PackageFeaturesAPIView(APIView):
    """GET / PUT /api/v1/billing/packages/{pk}/features/.

    Manage which features a package includes. Idempotent bulk replacement.
    """

    def get_permissions(self):
        if self.request.method in ("GET", "HEAD", "OPTIONS"):
            return [perm() for perm in PACKAGE_VIEW_PERMS]
        return [perm() for perm in PACKAGE_EDIT_PERMS]

    def get(self, request, pk):
        package = get_object_or_404(PlatformPackage, pk=pk)
        return Response({
            "package_id": package.id,
            "feature_ids": list(
                package.package_features.filter(is_enabled=True)
                .values_list("feature_id", flat=True)
            ),
        })

    def put(self, request, pk):
        package = get_object_or_404(PlatformPackage, pk=pk)
        serializer = PackageFeatureBulkSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        wanted = set(serializer.validated_data["feature_ids"])
        with transaction.atomic():
            existing = {
                pf.feature_id: pf
                for pf in package.package_features.all()
            }
            for fid in wanted:
                pf = existing.get(fid)
                if pf is None:
                    PlatformPackageFeature.objects.create(
                        package=package, feature_id=fid, is_enabled=True
                    )
                elif not pf.is_enabled:
                    pf.is_enabled = True
                    pf.save(update_fields=["is_enabled"])
            for fid, pf in existing.items():
                if fid not in wanted and pf.is_enabled:
                    pf.is_enabled = False
                    pf.save(update_fields=["is_enabled"])
        return Response({"status": "ok", "feature_count": len(wanted)})


class PaymentAPIView(ModelCRUDView):
    """Tenant payment CRUD under /api/v1/billing/payments/."""

    feature_key = 'payments'
    queryset = Payment.objects.select_related('member', 'member__member_package').all().order_by('-payment_date')
    serializer_class = PaymentSerializer
    permission_classes = [HasFeatureMethodPermission]

    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ['payment_type', 'payment_method', 'payment_status', 'member']
    search_fields = ['member__full_name', 'member__phone_number', 'member__email', 'invoice_no', 'note']
    ordering_fields = ['payment_date', 'amount', 'member__full_name', 'created_at']
    ordering = ['-payment_date']


class PaymentMemberListAPIView(APIView):
    """Member options for Add Payment form."""

    feature_key = 'payments'
    permission_classes = [HasFeatureMethodPermission]

    def get(self, request):
        members = Member.objects.select_related('member_package').all().order_by('full_name')
        return Response(PaymentMemberOptionSerializer(members, many=True).data)


class PaymentStatsAPIView(APIView):
    """Payment summary cards for dashboard payments page."""

    feature_key = 'payments'
    permission_classes = [HasFeatureMethodPermission]

    def get(self, request):
        payments = Payment.objects.all()

        totals = payments.aggregate(
            total_collected=Sum('amount', filter=Q(payment_status=Payment.STATUS_PAID)),
            total_due=Sum('amount', filter=Q(payment_status=Payment.STATUS_DUE)),
            partial_collected=Sum('amount', filter=Q(payment_status=Payment.STATUS_PARTIAL)),
            transaction_count=Count('id'),
            overdue_members=Count('member', filter=Q(payment_status=Payment.STATUS_DUE), distinct=True),
            partial_members=Count('member', filter=Q(payment_status=Payment.STATUS_PARTIAL), distinct=True),
        )

        now = timezone.now()
        month_start = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        previous_month_start = (month_start - timedelta(days=1)).replace(day=1)

        current_month_collected = payments.filter(
            payment_status=Payment.STATUS_PAID,
            payment_date__gte=month_start,
        ).aggregate(total=Sum('amount'))['total'] or Decimal('0')

        previous_month_collected = payments.filter(
            payment_status=Payment.STATUS_PAID,
            payment_date__gte=previous_month_start,
            payment_date__lt=month_start,
        ).aggregate(total=Sum('amount'))['total'] or Decimal('0')

        if previous_month_collected > 0:
            trend_percent = float(
                ((current_month_collected - previous_month_collected) / previous_month_collected) * 100
            )
        elif current_month_collected > 0:
            trend_percent = 100.0
        else:
            trend_percent = 0.0

        return Response({
            'total_collected': float(totals['total_collected'] or 0),
            'total_due': float(totals['total_due'] or 0),
            'partial_collected': float(totals['partial_collected'] or 0),
            'transaction_count': totals['transaction_count'] or 0,
            'overdue_members': totals['overdue_members'] or 0,
            'partial_members': totals['partial_members'] or 0,
            'trend_percent': round(trend_percent, 2),
        })


class PDFRenderer(BaseRenderer):
    media_type = 'application/pdf'
    format = 'pdf'
    charset = None
    render_style = 'binary'

    def render(self, data, accepted_media_type=None, renderer_context=None):
        if data is None:
            return b''
        if isinstance(data, bytes):
            return data
        return str(data).encode('utf-8')


class PaymentInvoicePdfAPIView(APIView):
    """Generate branded PDF invoice for manual payments."""

    feature_keys = ['payments', 'payments.invoices']
    permission_classes = [HasFeatureMethodPermission]
    renderer_classes = [PDFRenderer, JSONRenderer]

    def get(self, request, pk):
        payment = get_object_or_404(
            Payment.objects.select_related('member', 'member__member_package'),
            pk=pk,
        )

        if payment.payment_method != 'cash':
            return Response(
                {'detail': 'PDF invoice is available for manual (cash) payments only.'},
                status=status.HTTP_400_BAD_REQUEST,
            )

        tenant_name = getattr(getattr(request, 'tenant', None), 'name', None) or 'Fithive Gym'
        generated_by = getattr(request.user, 'full_name', '') or getattr(request.user, 'email', 'System')

        pdf_bytes = _render_payment_invoice_pdf(payment, tenant_name, generated_by)
        invoice_no = payment.invoice_no or f"INV-{payment.id:06d}"
        filename = f"invoice-{invoice_no}.pdf"
        disposition = 'attachment' if request.query_params.get('download') == '1' else 'inline'

        response = HttpResponse(pdf_bytes, content_type='application/pdf')
        response['Content-Disposition'] = f'{disposition}; filename="{filename}"'
        return response

