# Generated by Django 6.0.4 on 2026-05-30 14:14
# Hand-edited: migrate legacy GymClub records into gym_branch.Branch and
# repoint Contact.preferred_club -> Contact.preferred_branch before the
# legacy models are dropped. Runs only in tenant schemas (main_app is a
# TENANT app), so gym_branch tables are guaranteed to exist here.

import django.db.models.deletion
from django.db import migrations, models


def migrate_clubs_to_branches(apps, schema_editor):
    GymClub = apps.get_model('main_app', 'GymClub')
    Contact = apps.get_model('main_app', 'Contact')
    Branch = apps.get_model('gym_branch', 'Branch')
    Facility = apps.get_model('gym_branch', 'Facility')

    club_to_branch = {}
    for club in GymClub.objects.all():
        branch = Branch.objects.create(
            name=club.name,
            location=club.location,
            address=club.address or '',
            description=club.description,
            phone_number=club.phone_number or '',
            email=club.email,
            opening_time=club.opening_time,
            closing_time=club.closing_time,
            weekdays_hours=club.weekdays_hours,
            weekend_hours=club.weekend_hours,
            website=club.website,
            show_on_homepage=club.show_on_homepage,
            display_order=club.display_order,
            is_active=club.is_active,
            image=club.image,
            homepage_image=club.homepage_image,
            status='active',
        )
        for facility in club.facilities.all():
            new_facility, _ = Facility.objects.get_or_create(name=facility.name)
            branch.facilities.add(new_facility)
        club_to_branch[club.id] = branch

    # Ensure every tenant has a "Main Branch" to anchor existing members/trainers.
    default_branch = Branch.objects.filter(name='Main Branch').first()
    if default_branch is None:
        default_branch = Branch.objects.create(name='Main Branch', status='active')

    # Repoint contacts that referenced a legacy club.
    for contact in Contact.objects.exclude(preferred_club__isnull=True):
        branch = club_to_branch.get(contact.preferred_club_id)
        if branch is not None:
            contact.preferred_branch = branch
            contact.save(update_fields=['preferred_branch'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gym_branch', '0001_initial'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='preferred_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='gym_branch.branch'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page_name',
            field=models.CharField(help_text="Internal page identifier, e.g. 'Home', 'About', 'Branches'", max_length=100, unique=True),
        ),
        migrations.RunPython(migrate_clubs_to_branches, noop_reverse),
        migrations.RemoveField(
            model_name='gymclub',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='preferred_club',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='GymClub',
        ),
    ]
