# Generated by Django 5.2 on 2026-02-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_blog_excerpt_blog_is_show_on_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='is_show_on_home_page',
            field=models.BooleanField(default=True),
        ),
    ]
