# Generated by Django 5.2 on 2026-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitHiveSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('interested_in', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('responded', 'Responded')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
