# Generated by Django 5.2 on 2026-02-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_package_packageaddon_packagefeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymclub',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='gymclub',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymclub',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gymclub',
            name='homepage_image',
            field=models.ImageField(blank=True, null=True, upload_to='gym_clubs/homepage/'),
        ),
        migrations.AddField(
            model_name='gymclub',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gymclub',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='gymclub',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gymclub',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymclub',
            name='weekdays_hours',
            field=models.CharField(blank=True, help_text='e.g., 6:00AM-10:00PM', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gymclub',
            name='weekend_hours',
            field=models.CharField(blank=True, help_text='e.g., 6:00AM-10:00PM', max_length=50, null=True),
        ),
    ]
