# Generated by Django 5.2 on 2026-04-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_gymclub_closing_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text="Internal page identifier, e.g. 'Home', 'About', 'Clubs'", max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('hero_image', models.URLField(blank=True, help_text='Hero/header image URL', max_length=1000)),
                ('content', models.TextField(blank=True, help_text='Main page content (may contain HTML)')),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page_name'],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('top_bar', 'Top Bar'), ('popup_modal', 'Popup Modal')], default='top_bar', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='Primary/fallback image URL', max_length=1000)),
                ('desktop_image_url', models.URLField(blank=True, max_length=1000)),
                ('tablet_image_url', models.URLField(blank=True, max_length=1000)),
                ('mobile_image_url', models.URLField(blank=True, max_length=1000)),
                ('link_url', models.CharField(blank=True, help_text='Target URL when the banner is clicked', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, help_text='Date from which the banner is visible', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Date after which the banner is hidden', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading shown on the banner', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Label/badge above the title', max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('desktop_url', models.URLField(help_text='Media URL for desktop (1920×1080). Required.', max_length=1000)),
                ('laptop_url', models.URLField(blank=True, help_text='Media URL for laptop (1366×768)', max_length=1000)),
                ('tablet_url', models.URLField(blank=True, help_text='Media URL for tablet (768×1024)', max_length=1000)),
                ('mobile_url', models.URLField(blank=True, help_text='Media URL for mobile (375×667)', max_length=1000)),
                ('cta_text', models.CharField(blank=True, help_text='Call-to-action button label', max_length=100)),
                ('cta_link', models.CharField(blank=True, help_text='Call-to-action URL or path', max_length=500)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order; lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, max_length=1000)),
                ('logo_width', models.PositiveIntegerField(default=120, help_text='Logo display width in pixels')),
                ('logo_height', models.PositiveIntegerField(default=40, help_text='Logo display height in pixels')),
                ('navbar_pages', models.JSONField(blank=True, default=list, help_text='Ordered list of {page_name, label, order} objects for the navbar')),
                ('footer_pages', models.JSONField(blank=True, default=list, help_text='Ordered list of {page_name, label, order} objects for the footer')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
