"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import socket
from pathlib import Path
from datetime import timedelta
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _is_running_in_docker() -> bool:
    return Path('/.dockerenv').exists()


def _first_resolvable_host(host_candidates):
    for host in host_candidates:
        if not host:
            continue
        try:
            socket.getaddrinfo(host, None)
            return host
        except OSError:
            continue
    return None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-s5gp6lsw-mzturp2^ku5$th^q#f0-^dk7za2a#u^)a)62y@8=j',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'false').lower() in ('true', '1')

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('ALLOWED_HOSTS', '*').split(',')
    if h.strip()
]

# ---------------------------------------------------------------
# Application definition — django-tenants split
#
# SHARED_APPS  → tables created once in the public (shared) schema.
# TENANT_APPS  → tables created inside every tenant's own schema.
# INSTALLED_APPS is derived automatically (union, no duplicates).
# ---------------------------------------------------------------

# Apps that live in the PUBLIC (shared) PostgreSQL schema
SHARED_APPS = [
    'django_tenants',               # must be first
    'apps.tenancy',                  # Tenant + Domain models

    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.identity.apps.IdentityConfig',

    'rest_framework',
    'corsheaders',
    'drf_spectacular',
]

# Apps whose tables are replicated inside EACH tenant schema
TENANT_APPS = [
    'django.contrib.contenttypes',   # needed for permissions in tenant schema
    'django.contrib.auth',
    'apps.identity.apps.IdentityConfig',
    'apps.access.apps.AccessConfig',
    'apps.dashboard.apps.DashboardConfig',
    'apps.membership.apps.MembershipConfig',
    'apps.quick_action.apps.QuickActionConfig',
    'apps.cms.apps.CmsConfig',
    'apps.crm.apps.CrmConfig',
    'apps.billing.apps.BillingConfig',
    'apps.attendance.apps.AttendanceConfig',
    'apps.trainer.apps.TrainerConfig',
]

# Django requires a flat INSTALLED_APPS list; django-tenants merges both lists
INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

INSTALLED_APPS += [
    'channels',
]

# django-tenants settings
TENANT_MODEL = 'tenancy.Tenant'
TENANT_DOMAIN_MODEL = 'tenancy.Domain'
# URL conf used when the request resolves to the public (shared) schema
PUBLIC_SCHEMA_URLCONF = 'config.public_urls'
# Route tenant-app migrations to the correct schema
DATABASE_ROUTERS = ['django_tenants.routers.TenantSyncRouter']
# Let localhost healthchecks and unknown hosts resolve to the public schema
# instead of failing inside TenantMainMiddleware.
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True

MIDDLEWARE = [
    # TenantMainMiddleware resolves the tenant from the request hostname
    # and activates the correct PostgreSQL schema before any view runs.
    # It must be the very first middleware in the stack.
    'django_tenants.middleware.main.TenantMainMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

_cors_allow_all = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'true').lower() in ('true', '1')
CORS_ALLOW_ALL_ORIGINS = _cors_allow_all
if not _cors_allow_all:
    CORS_ALLOWED_ORIGINS = [
        o.strip()
        for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
        if o.strip()
    ]

    # Keep local frontend ports working when CORS is restricted but no explicit
    # local origins were provided in env.
    if DEBUG and not CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS = [
            'http://localhost:5173',
            'http://localhost:5174',
            'http://127.0.0.1:5173',
            'http://127.0.0.1:5174',
        ]

# Support cookie/session-based auth flows across origins when needed.
CORS_ALLOW_CREDENTIALS = os.environ.get('CORS_ALLOW_CREDENTIALS', 'true').lower() in ('true', '1')

_cors_allowed_origin_regexes = [
    o.strip()
    for o in os.environ.get('CORS_ALLOWED_ORIGIN_REGEXES', '').split(',')
    if o.strip()
]
if _cors_allowed_origin_regexes:
    CORS_ALLOWED_ORIGIN_REGEXES = _cors_allowed_origin_regexes
elif not DEBUG:
    # Production-friendly default to allow wildcard tenant subdomains.
    root_domain = os.environ.get('TENANT_ROOT_DOMAIN', 'musfiqdehan.com').strip().replace('.', r'\.')
    CORS_ALLOWED_ORIGIN_REGEXES = [
        rf'^https://([a-z0-9-]+\.)?{root_domain}$',
    ]

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]

# Trust HTTPS termination at the reverse proxy so CSRF referer/origin
# validation and secure cookie behavior work correctly in production.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'false').lower() in ('true', '1')

# Tenant auth helper settings
PUBLIC_DOMAIN = os.environ.get('PUBLIC_DOMAIN', '').strip().lower()
TENANT_BASE_DOMAIN = os.environ.get('TENANT_BASE_DOMAIN', '').strip().lower()
TENANT_POST_LOGIN_PATH = os.environ.get('TENANT_POST_LOGIN_PATH', '/dashboard').strip() or '/dashboard'
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', '').strip()
PUBLIC_FRONTEND_URL = os.environ.get('PUBLIC_FRONTEND_URL', FRONTEND_BASE_URL).strip()
TENANT_FRONTEND_BASE_DOMAIN = os.environ.get('TENANT_FRONTEND_BASE_DOMAIN', TENANT_BASE_DOMAIN).strip().lower()
TENANT_FRONTEND_SCHEME = os.environ.get('TENANT_FRONTEND_SCHEME', 'http' if DEBUG else 'https').strip().lower() or ('http' if DEBUG else 'https')
TENANT_FRONTEND_PORT = os.environ.get('TENANT_FRONTEND_PORT', '').strip()
TENANT_ONBOARDING_LINKS_PUBLIC = os.environ.get('TENANT_ONBOARDING_LINKS_PUBLIC', 'false').lower() in ('true', '1')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# When DATABASE_URL is set (e.g. from Docker env), PostgreSQL is used.
# Falls back to SQLite for development without Docker.

# django-tenants requires PostgreSQL with a schema-aware backend.
# When DATABASE_URL is set (e.g. via Docker), it takes priority.
# Otherwise fall back to explicit env vars for local dev with PostgreSQL.
_database_url = os.environ.get('DATABASE_URL', '')
if _database_url:
    _db_cfg = dj_database_url.parse(
        _database_url,
        conn_max_age=600,
        conn_health_checks=True,
    )

    # If Django runs on the host machine, Docker service names like "db"
    # are not resolvable. Remap to localhost (host-mapped port) for local use.
    db_host = _db_cfg.get('HOST')

    if not _is_running_in_docker() and db_host in {'db', 'postgres', 'postgresql', 'gym-db-local'}:
        _db_cfg['HOST'] = os.environ.get('LOCAL_DB_HOST', 'localhost')
        if not os.environ.get('LOCAL_DB_PORT') and str(_db_cfg.get('PORT') or '') in {'', '5432'}:
            _db_cfg['PORT'] = '5451'
        else:
            _db_cfg['PORT'] = os.environ.get('LOCAL_DB_PORT', _db_cfg.get('PORT'))

    if _is_running_in_docker():
        in_docker_host = _db_cfg.get('HOST')
        fallback_hosts = [
            in_docker_host,
            os.environ.get('DOCKER_DB_HOST', ''),
            os.environ.get('POSTGRES_HOST', ''),
            'gym-db-local',
            'db',
            'postgres',
        ]
        resolved_host = _first_resolvable_host(fallback_hosts)
        if resolved_host:
            _db_cfg['HOST'] = resolved_host

    _db_cfg['ENGINE'] = 'django_tenants.postgresql_backend'
    DATABASES = {'default': _db_cfg}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django_tenants.postgresql_backend',
            'NAME': os.environ.get('DB_NAME', 'gymapp_db'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# -------------------
# Static files (served by whitenoise)
# -------------------
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# -------------------
# Media files (local filesystem — works on both dev PC and cloud server)
# Uploaded files are stored in /app/media inside the container,
# which is bind-mounted or backed by a named Docker volume.
# -------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Channels (Redis-backed)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [
                (
                    os.environ.get('REDIS_HOST', 'redis'),
                    int(os.environ.get('REDIS_PORT', '6379')),
                )
            ],
        },
    }
}

# Celery
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://redis:6379/1')
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.environ.get('CELERY_TASK_TIME_LIMIT', '300'))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.environ.get('CELERY_TASK_SOFT_TIME_LIMIT', '240'))
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST_FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # "rest_framework.authentication.SessionAuthentication",
        # "rest_framework.authentication.TokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        # "rest_framework.permissions.IsAuthenticated",
        "rest_framework.permissions.AllowAny",
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'tenant_registration': '10/hour',
        'tenant_auth': '30/minute',
        'tenant_password_reset': '10/hour',
        'tenant_password_setup': '20/hour',
        'superadmin_invitation': '60/hour',
    },
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=2),   
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), 
    'AUTH_HEADER_TYPES': ('Bearer',),
}
# user model
AUTH_USER_MODEL = 'identity.User'

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Gym Management System API',
    'DESCRIPTION': 'API documentation for the GeeksSort Gym Management System',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{'bearerAuth': []}],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
}

# Email Configuration
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False') == 'True'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', 15))
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', os.environ.get('EMAIL_HOST_USER', 'noreply@example.com'))

# ADMS device logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "apps.attendance": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
