# Generated by Django 5.2 on 2026-02-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_gymclub_options_gymclub_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclub',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymclub',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
