# Generated by Django 5.2 on 2026-04-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_pagecontent_promobanner_sitebanner_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(blank=True, help_text='Optional company name shown in navbar/footer', max_length=200),
        ),
    ]
