# Generated by Django 5.2 on 2026-04-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_gym_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbooking',
            name='booking_date',
            field=models.DateField(blank=True, help_text='Computed next occurrence date for the selected schedule', null=True),
        ),
        migrations.AddField(
            model_name='classbooking',
            name='selected_schedule',
            field=models.ForeignKey(blank=True, help_text='Which schedule slot the user booked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main_app.classschedule'),
        ),
    ]
