# Generated by Django 6.0.4 on 2026-05-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_update_models_with_base_and_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberpackage',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
