# Generated by Django 6.0.4 on 2026-05-12 08:17

import django.utils.timezone
from django.db import migrations, models


def add_payment_columns_if_missing(apps, schema_editor):
    table = 'membership_payment'
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(cursor, table)
        existing_columns = {col.name for col in description}

    statements = []
    if 'invoice_no' not in existing_columns:
        statements.append(
            "ALTER TABLE membership_payment ADD COLUMN invoice_no varchar(64) NULL"
        )
    if 'payment_method' not in existing_columns:
        statements.append(
            "ALTER TABLE membership_payment ADD COLUMN payment_method varchar(20) NOT NULL DEFAULT 'cash'"
        )
    if 'payment_status' not in existing_columns:
        statements.append(
            "ALTER TABLE membership_payment ADD COLUMN payment_status varchar(20) NOT NULL DEFAULT 'due'"
        )

    for sql in statements:
        schema_editor.execute(sql)

    # Align DB-level uniqueness with the model's unique=True on invoice_no.
    schema_editor.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS membership_payment_invoice_no_uniq "
        "ON membership_payment (invoice_no)"
    )


def sync_payment_status_from_is_paid(apps, schema_editor):
    Payment = apps.get_model('membership', 'Payment')
    Payment.objects.filter(is_paid=True).update(payment_status='paid')
    Payment.objects.filter(is_paid=False).update(payment_status='due')


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_alter_member_options_alter_memberpackage_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_payment_columns_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='payment',
                    name='invoice_no',
                    field=models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='payment_method',
                    field=models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('card', 'Card'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=20),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='payment_status',
                    field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partially Paid'), ('due', 'Due')], default='due', max_length=20),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('admission', 'Admission Fee'), ('package', 'Package Payment'), ('monthly', 'Monthly Payment'), ('other', 'Other')], max_length=20),
        ),
        migrations.RunPython(sync_payment_status_from_is_paid, migrations.RunPython.noop),
    ]
