# Generated by Django 6.0.4 on 2026-05-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_add_gymclass_gymschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]