# Generated by Django 6.0.4 on 2026-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_gymclass_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('card', 'Card'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('sslcommerz', 'SSLCommerz'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
