# Generated by Django 6.0.4 on 2026-06-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_query_optimization_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='relationship_with_member',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
