# Generated by Django 6.0.4 on 2026-07-14 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0018_payment_coverage_months_line_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active and usable')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this item is published/visible')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount'), ('fixed_price', 'Fixed Price'), ('buy_x_get_y', 'Buy X Get Y'), ('tiered', 'Tiered / Volume'), ('free_addon', 'Free Add-on')], max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('application_mode', models.CharField(choices=[('automatic', 'Automatic'), ('coupon', 'Coupon'), ('both', 'Both')], default='automatic', max_length=16)),
                ('coupon_code', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('is_stackable', models.BooleanField(default=False)),
                ('stack_group', models.CharField(blank=True, default='', max_length=64)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('condition_logic', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=8)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit_total', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_limit_per_member', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active and usable')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this item is published/visible')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('field', models.CharField(max_length=64)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('neq', 'Not equals'), ('in', 'In'), ('gte', 'Greater or equal'), ('lte', 'Less or equal'), ('between', 'Between')], default='eq', max_length=16)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='membership.discount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code_used', models.CharField(blank=True, default='', max_length=64)),
                ('amount_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='membership.discount')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_usages', to='membership.member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='membership.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['is_active', 'is_deleted', 'priority'], name='idx_discount_active_priority'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('coupon_code', None), _negated=True), models.Q(('coupon_code', ''), _negated=True)), fields=('coupon_code',), name='uniq_discount_coupon_code_active'),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['discount', 'created_at'], name='idx_dusage_discount_created'),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['member', 'discount'], name='idx_dusage_member_discount'),
        ),
        migrations.AddConstraint(
            model_name='discountusage',
            constraint=models.UniqueConstraint(fields=('payment', 'discount'), name='uniq_discount_usage_payment'),
        ),
    ]
