# Generated by Django 6.0.4 on 2026-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0019_discount_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="show_list_price",
            field=models.BooleanField(
                default=False,
                help_text="Show strikethrough original + discounted price on package listings",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="show_percent_badge",
            field=models.BooleanField(
                default=False,
                help_text="Show percent-off badge on package listings (percentage discounts)",
            ),
        ),
    ]
