# Generated by Django 6.0.4 on 2026-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0020_discount_list_display_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='coupon_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='coupon_code_used',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
