# Generated by Django 5.2 on 2026-02-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0002_remove_member_address_remove_member_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('package', 'Package'), ('monthly', 'Monthly Only')], default='monthly', max_length=20),
        ),
    ]
