# Generated by Django 5.2 on 2026-02-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0003_member_membership_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='MemberPackage',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='package',
            new_name='member_package',
        ),
    ]
