# Generated by Django 6.0.4 on 2026-07-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_deviceuser_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceuser',
            name='status',
            field=models.CharField(choices=[('unlinked', 'Unlinked'), ('linked', 'Linked'), ('pending_delete', 'Pending delete'), ('deleted', 'Deleted')], default='unlinked', max_length=20),
        ),
    ]
