from django.urls import path
from .views import (
    DashboardBlogListAPIView,
    DashboardBlogCreateAPIView,
    DashboardBlogRetrieveAPIView,
    DashboardBlogUpdateAPIView,
    DashboardBlogDeleteAPIView,
    DashboardBlogCategoryListAPIView,
    DashboardBlogCategoryCreateAPIView,
    DashboardBlogCategoryRetrieveAPIView,
    DashboardBlogCategoryUpdateAPIView,
    DashboardBlogCategoryDeleteAPIView,
    GymClassDashboardListAPIView,
    GymClassDashboardCreateAPIView,
    GymClassDashboardRetrieveAPIView,
    GymClassDashboardUpdateAPIView,
    GymClassDashboardDeleteAPIView,
    GymClassLevelsAPIView,
    ClassBookingListAPIView,
    ClassBookingCreateAPIView,
    ClassBookingRetrieveAPIView,
    ClassBookingUpdateAPIView,
    ClassBookingDeleteAPIView,
    GymClassCategoryDashboardListAPIView,
    GymClassCategoryDashboardCreateAPIView,
    GymClassCategoryDashboardRetrieveAPIView,
    GymClassCategoryDashboardUpdateAPIView,
    GymClassCategoryDashboardDeleteAPIView,
    DashboardContactListAPIView,
    DashboardContactCreateAPIView,
    DashboardContactRetrieveAPIView,
    DashboardContactUpdateAPIView,
    DashboardContactDeleteAPIView,
    DashboardContactMarkAsReadAPIView,
    DashboardContactMarkAsRespondedAPIView,
    DashboardContactNewListAPIView,
    DashboardContactReadListAPIView,
    DashboardContactRespondedListAPIView,
    DashboardFitHiveSupportListAPIView,
    DashboardFitHiveSupportCreateAPIView,
    DashboardFitHiveSupportRetrieveAPIView,
    DashboardFitHiveSupportUpdateAPIView,
    DashboardFitHiveSupportDeleteAPIView,
    DashboardFitHiveSupportMarkAsReadAPIView,
    DashboardFitHiveSupportMarkAsRespondedAPIView,
    PackageListAPIView,
    PackageCreateAPIView,
    PackageRetrieveAPIView,
    PackageUpdateAPIView,
    PackageDeleteAPIView,
    GymClubDashboardListAPIView,
    GymClubDashboardCreateAPIView,
    GymClubDashboardRetrieveAPIView,
    GymClubDashboardUpdateAPIView,
    GymClubDashboardDeleteAPIView,
    PackageDashboardListAPIView,
    PackageDashboardCreateAPIView,
    PackageDashboardRetrieveAPIView,
    PackageDashboardUpdateAPIView,
    PackageDashboardDeleteAPIView,
    MemberDashboardListAPIView,
    MemberDashboardCreateAPIView,
    MemberDashboardRetrieveAPIView,
    MemberDashboardUpdateAPIView,
    MemberDashboardDeleteAPIView,
    PaymentDashboardListAPIView,
    PaymentDashboardCreateAPIView,
    PaymentDashboardRetrieveAPIView,
    PaymentDashboardUpdateAPIView,
    PaymentDashboardDeleteAPIView,
    AttendanceDashboardListAPIView,
    AttendanceDashboardCreateAPIView,
    AttendanceDashboardRetrieveAPIView,
    AttendanceDashboardUpdateAPIView,
    AttendanceDashboardDeleteAPIView,
    SiteBannerListAPIView,
    SiteBannerCreateAPIView,
    SiteBannerRetrieveAPIView,
    SiteBannerUpdateAPIView,
    SiteBannerDeleteAPIView,
    PromoBannerListAPIView,
    PromoBannerCreateAPIView,
    PromoBannerRetrieveAPIView,
    PromoBannerUpdateAPIView,
    PromoBannerDeleteAPIView,
    SiteSettingsAPIView,
    PageContentListAPIView,
    PageContentCreateAPIView,
    PageContentRetrieveAPIView,
    PageContentUpdateAPIView,
    PageContentDeleteAPIView,
    FileUploadView,
    GymScheduleDashboardListAPIView,
    GymScheduleDashboardCreateAPIView,
    GymScheduleDashboardRetrieveAPIView,
    GymScheduleDashboardUpdateAPIView,
    GymScheduleDashboardDeleteAPIView,
)
from apps.identity.views import InstructorListAPIView

app_name = 'dashboard'

urlpatterns = [
    path('blogs/', DashboardBlogListAPIView.as_view(), name='blog-list'),
    path('blogs/create/', DashboardBlogCreateAPIView.as_view(), name='blog-create'),
    path('blogs/<int:pk>/', DashboardBlogRetrieveAPIView.as_view(), name='blog-detail'),
    path('blogs/<int:pk>/update/', DashboardBlogUpdateAPIView.as_view(), name='blog-update'),
    path('blogs/<int:pk>/delete/', DashboardBlogDeleteAPIView.as_view(), name='blog-delete'),
    path('blog-categories/', DashboardBlogCategoryListAPIView.as_view(), name='blog-category-list'),
    path('blog-categories/create/', DashboardBlogCategoryCreateAPIView.as_view(), name='blog-category-create'),
    path('blog-categories/<int:pk>/', DashboardBlogCategoryRetrieveAPIView.as_view(), name='blog-category-detail'),
    path('blog-categories/<int:pk>/update/', DashboardBlogCategoryUpdateAPIView.as_view(), name='blog-category-update'),
    path('blog-categories/<int:pk>/delete/', DashboardBlogCategoryDeleteAPIView.as_view(), name='blog-category-delete'),
    path('gym-classes/', GymClassDashboardListAPIView.as_view(), name='gym-class-list'),
    path('gym-classes/create/', GymClassDashboardCreateAPIView.as_view(), name='gym-class-create'),
    path('gym-classes/levels/', GymClassLevelsAPIView.as_view(), name='gym-class-levels'),
    path('gym-classes/<int:pk>/', GymClassDashboardRetrieveAPIView.as_view(), name='gym-class-detail'),
    path('gym-classes/<int:pk>/update/', GymClassDashboardUpdateAPIView.as_view(), name='gym-class-update'),
    path('gym-classes/<int:pk>/delete/', GymClassDashboardDeleteAPIView.as_view(), name='gym-class-delete'),
    path('class-bookings/', ClassBookingListAPIView.as_view(), name='class-booking-list'),
    path('class-bookings/create/', ClassBookingCreateAPIView.as_view(), name='class-booking-create'),
    path('class-bookings/<int:pk>/', ClassBookingRetrieveAPIView.as_view(), name='class-booking-detail'),
    path('class-bookings/<int:pk>/update/', ClassBookingUpdateAPIView.as_view(), name='class-booking-update'),
    path('class-bookings/<int:pk>/delete/', ClassBookingDeleteAPIView.as_view(), name='class-booking-delete'),
    path('gym-class-categories/', GymClassCategoryDashboardListAPIView.as_view(), name='gym-class-category-list'),
    path('gym-class-categories/create/', GymClassCategoryDashboardCreateAPIView.as_view(), name='gym-class-category-create'),
    path('gym-class-categories/<int:pk>/', GymClassCategoryDashboardRetrieveAPIView.as_view(), name='gym-class-category-detail'),
    path('gym-class-categories/<int:pk>/update/', GymClassCategoryDashboardUpdateAPIView.as_view(), name='gym-class-category-update'),
    path('gym-class-categories/<int:pk>/delete/', GymClassCategoryDashboardDeleteAPIView.as_view(), name='gym-class-category-delete'),
    path('instructors/', InstructorListAPIView.as_view(), name='instructor-list'),
    path('contacts/', DashboardContactListAPIView.as_view(), name='contact-list'),
    path('contacts/create/', DashboardContactCreateAPIView.as_view(), name='contact-create'),
    path('contacts/new/', DashboardContactNewListAPIView.as_view(), name='contact-new-list'),
    path('contacts/read/', DashboardContactReadListAPIView.as_view(), name='contact-read-list'),
    path('contacts/responded/', DashboardContactRespondedListAPIView.as_view(), name='contact-responded-list'),
    path('contacts/<int:pk>/', DashboardContactRetrieveAPIView.as_view(), name='contact-detail'),
    path('contacts/<int:pk>/update/', DashboardContactUpdateAPIView.as_view(), name='contact-update'),
    path('contacts/<int:pk>/delete/', DashboardContactDeleteAPIView.as_view(), name='contact-delete'),
    path('contacts/<int:pk>/mark-as-read/', DashboardContactMarkAsReadAPIView.as_view(), name='contact-mark-as-read'),
    path('contacts/<int:pk>/mark-as-responded/', DashboardContactMarkAsRespondedAPIView.as_view(), name='contact-mark-as-responded'),
    path('fithive-support/', DashboardFitHiveSupportListAPIView.as_view(), name='fithive-support-list'),
    path('fithive-support/create/', DashboardFitHiveSupportCreateAPIView.as_view(), name='fithive-support-create'),
    path('fithive-support/<int:pk>/', DashboardFitHiveSupportRetrieveAPIView.as_view(), name='fithive-support-detail'),
    path('fithive-support/<int:pk>/update/', DashboardFitHiveSupportUpdateAPIView.as_view(), name='fithive-support-update'),
    path('fithive-support/<int:pk>/delete/', DashboardFitHiveSupportDeleteAPIView.as_view(), name='fithive-support-delete'),
    path('fithive-support/<int:pk>/mark-as-read/', DashboardFitHiveSupportMarkAsReadAPIView.as_view(), name='fithive-support-mark-as-read'),
    path('fithive-support/<int:pk>/mark-as-responded/', DashboardFitHiveSupportMarkAsRespondedAPIView.as_view(), name='fithive-support-mark-as-responded'),
    path('packages/', PackageListAPIView.as_view(), name='package-list'),
    path('packages/create/', PackageCreateAPIView.as_view(), name='package-create'),
    path('packages/<int:pk>/', PackageRetrieveAPIView.as_view(), name='package-detail'),
    path('packages/<int:pk>/update/', PackageUpdateAPIView.as_view(), name='package-update'),
    path('packages/<int:pk>/delete/', PackageDeleteAPIView.as_view(), name='package-delete'),
    path('gym-club/', GymClubDashboardListAPIView.as_view(), name='gym-club-list'),
    path('gym-club/create/', GymClubDashboardCreateAPIView.as_view(), name='gym-club-create'),
    path('gym-club/<int:pk>/', GymClubDashboardRetrieveAPIView.as_view(), name='gym-club-detail'),
    path('gym-club/<int:pk>/update/', GymClubDashboardUpdateAPIView.as_view(), name='gym-club-update'),
    path('gym-club/<int:pk>/delete/', GymClubDashboardDeleteAPIView.as_view(), name='gym-club-delete'),
    path('members/', MemberDashboardListAPIView.as_view(), name='member-list'),
    path('members/create/', MemberDashboardCreateAPIView.as_view(), name='member-create'),
    path('members/<int:pk>/', MemberDashboardRetrieveAPIView.as_view(), name='member-detail'),
    path('members/<int:pk>/update/', MemberDashboardUpdateAPIView.as_view(), name='member-update'),
    path('members/<int:pk>/delete/', MemberDashboardDeleteAPIView.as_view(), name='member-delete'),
    path('member-packages/', PackageDashboardListAPIView.as_view(), name='member-package-list'),
    path('member-packages/create/', PackageDashboardCreateAPIView.as_view(), name='member-package-create'),
    path('member-packages/<int:pk>/', PackageDashboardRetrieveAPIView.as_view(), name='member-package-detail'),
    path('member-packages/<int:pk>/update/', PackageDashboardUpdateAPIView.as_view(), name='member-package-update'),
    path('member-packages/<int:pk>/delete/', PackageDashboardDeleteAPIView.as_view(), name='member-package-delete'),
    path('payments/', PaymentDashboardListAPIView.as_view(), name='payment-list'),
    path('payments/create/', PaymentDashboardCreateAPIView.as_view(), name='payment-create'),
    path('payments/<int:pk>/', PaymentDashboardRetrieveAPIView.as_view(), name='payment-detail'),
    path('payments/<int:pk>/update/', PaymentDashboardUpdateAPIView.as_view(), name='payment-update'),
    path('payments/<int:pk>/delete/', PaymentDashboardDeleteAPIView.as_view(), name='payment-delete'),
    path('attendance/', AttendanceDashboardListAPIView.as_view(), name='attendance-list'),
    path('attendance/create/', AttendanceDashboardCreateAPIView.as_view(), name='attendance-create'),
    path('attendance/<int:pk>/', AttendanceDashboardRetrieveAPIView.as_view(), name='attendance-detail'),
    path('attendance/<int:pk>/update/', AttendanceDashboardUpdateAPIView.as_view(), name='attendance-update'),
    path('attendance/<int:pk>/delete/', AttendanceDashboardDeleteAPIView.as_view(), name='attendance-delete'),
    path('site-banners/', SiteBannerListAPIView.as_view(), name='site-banner-list'),
    path('site-banners/create/', SiteBannerCreateAPIView.as_view(), name='site-banner-create'),
    path('site-banners/<int:pk>/', SiteBannerRetrieveAPIView.as_view(), name='site-banner-detail'),
    path('site-banners/<int:pk>/update/', SiteBannerUpdateAPIView.as_view(), name='site-banner-update'),
    path('site-banners/<int:pk>/delete/', SiteBannerDeleteAPIView.as_view(), name='site-banner-delete'),
    path('promo-banners/', PromoBannerListAPIView.as_view(), name='promo-banner-list'),
    path('promo-banners/create/', PromoBannerCreateAPIView.as_view(), name='promo-banner-create'),
    path('promo-banners/<int:pk>/', PromoBannerRetrieveAPIView.as_view(), name='promo-banner-detail'),
    path('promo-banners/<int:pk>/update/', PromoBannerUpdateAPIView.as_view(), name='promo-banner-update'),
    path('promo-banners/<int:pk>/delete/', PromoBannerDeleteAPIView.as_view(), name='promo-banner-delete'),
    path('site-settings/', SiteSettingsAPIView.as_view(), name='site-settings'),
    path('page-content/', PageContentListAPIView.as_view(), name='page-content-list'),
    path('page-content/create/', PageContentCreateAPIView.as_view(), name='page-content-create'),
    path('page-content/<int:pk>/', PageContentRetrieveAPIView.as_view(), name='page-content-detail'),
    path('page-content/<int:pk>/update/', PageContentUpdateAPIView.as_view(), name='page-content-update'),
    path('page-content/<int:pk>/delete/', PageContentDeleteAPIView.as_view(), name='page-content-delete'),
    path('gym-schedules/', GymScheduleDashboardListAPIView.as_view(), name='gym-schedule-list'),
    path('gym-schedules/create/', GymScheduleDashboardCreateAPIView.as_view(), name='gym-schedule-create'),
    path('gym-schedules/<int:pk>/', GymScheduleDashboardRetrieveAPIView.as_view(), name='gym-schedule-detail'),
    path('gym-schedules/<int:pk>/update/', GymScheduleDashboardUpdateAPIView.as_view(), name='gym-schedule-update'),
    path('gym-schedules/<int:pk>/delete/', GymScheduleDashboardDeleteAPIView.as_view(), name='gym-schedule-delete'),
    path('upload/', FileUploadView.as_view(), name='file-upload'),
]
