# Generated by Django 6.0.4 on 2026-06-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('tenant_registered', 'Tenant Registered'), ('tenant_subscribed', 'Tenant Subscribed'), ('member_onboarded', 'Member Onboarded'), ('trainer_onboarded', 'Trainer Onboarded'), ('welcome_member', 'Welcome Member'), ('welcome_trainer', 'Welcome Trainer'), ('class_booking_confirmed', 'Class Booking Confirmed'), ('class_enrollment_confirmed', 'Class Enrollment Confirmed'), ('new_booking_received', 'New Booking Received'), ('booking_cancelled', 'Booking Cancelled'), ('payment_confirmed', 'Payment Confirmed'), ('payment_received', 'Payment Received'), ('subscription_payment_confirmed', 'Subscription Payment Confirmed')], max_length=50),
        ),
    ]
