# Generated by Django 6.0.4 on 2026-05-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promobanner',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='promobanner',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Accessible description for the promo image', max_length=255),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='cta_text',
            field=models.CharField(blank=True, default='', help_text='Optional call-to-action label', max_length=100),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Secondary text shown on the promo banner', max_length=200),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Primary text shown on the promo banner', max_length=200),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitebanner',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Accessible description for the banner media', max_length=255),
        ),
        migrations.AddField(
            model_name='sitebanner',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date after which the banner is hidden', null=True),
        ),
        migrations.AddField(
            model_name='sitebanner',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date from which the banner is visible', null=True),
        ),
    ]
