# Generated by Django 6.0.4 on 2026-05-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_delete_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page_name',
            field=models.CharField(help_text="Internal page identifier, e.g. 'Home', 'About', 'Branches'", max_length=100, unique=True),
        ),
    ]
