# Generated by Django 6.0.4 on 2026-05-08 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False, help_text='System roles (e.g. admin/manager) cannot be deleted.')),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=120)),
                ('permission_level', models.CharField(choices=[('none', 'None'), ('view', 'View'), ('edit', 'Edit'), ('full', 'Full')], default='view', max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='access.role')),
            ],
            options={
                'indexes': [models.Index(fields=['feature_key'], name='access_role_feature_36ed60_idx')],
                'unique_together': {('role', 'feature_key')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='access.role')),
            ],
            options={
                'indexes': [models.Index(fields=['user_email'], name='access_user_user_em_537793_idx')],
                'unique_together': {('user_id', 'role')},
            },
        ),
    ]
