# Generated by Django 6.0.4 on 2026-06-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_branch', '0001_initial'),
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_roles', to='gym_branch.branch'),
        ),
    ]
