# Generated by Django 6.0.4 on 2026-05-30 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0010_alter_payment_payment_method'),
        ('trainer', '0002_alter_trainerdocument_document_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active and usable')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this item is published/visible')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, default='', help_text='Short branch code, e.g. GLS-01.', max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('operating_hours', models.CharField(blank=True, default='', help_text="Display hours, e.g. '06:00 — 23:00'.", max_length=100)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('weekdays_hours', models.CharField(blank=True, help_text='e.g., 6:00AM-10:00PM', max_length=50, null=True)),
                ('weekend_hours', models.CharField(blank=True, help_text='e.g., 6:00AM-10:00PM', max_length=50, null=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('opening_soon', 'Opening Soon'), ('closed', 'Closed')], default='active', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('staff_count', models.PositiveIntegerField(default=0)),
                ('classes_per_week', models.PositiveIntegerField(default=0)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_trend', models.FloatField(default=0.0, help_text='Percentage trend.')),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='branches/')),
                ('homepage_image', models.ImageField(blank=True, null=True, upload_to='branches/homepage/')),
                ('website', models.URLField(blank=True, null=True)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('is_flagship', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, help_text='Tenant user who manages this branch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('facilities', models.ManyToManyField(blank=True, related_name='branches', to='gym_branch.facility')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BranchShiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active and usable')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this item is published/visible')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('decision_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_requests_from', to='gym_branch.branch')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_shift_requests', to='membership.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_branch_shifts', to=settings.AUTH_USER_MODEL)),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests_to', to='gym_branch.branch')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_shift_requests', to='trainer.trainerprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
